---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/cards":
    get:
      summary: Lists cards
      tags:
      - Cards
      responses:
        '200':
          description: cards listed
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Card"
    post:
      summary: Creates a card
      tags:
      - Cards
      parameters: []
      responses:
        '201':
          description: card created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Card"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CardInput"
  "/api/owner/cards":
    post:
      summary: Creates a card
      tags:
      - Owner Cards
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: card created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OwnerCard"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CardInput"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    Card:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        pinyin:
          type: string
      required:
      - uuid
      - name
      - pinyin
    OwnerCard:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
        name:
          type: string
        pinyin:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - uuid
      - name
      - pinyin
      - created_at
      - updated_at
    CardInput:
      type: object
      properties:
        card:
          type: object
          properties:
            name:
              type: string
            pinyin:
              type: string
          required:
          - name
          - pinyin
      required:
      - card
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      required:
      - errors
