---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/cards":
    get:
      summary: Lists cards
      tags:
      - Cards
      responses:
        '200':
          description: cards listed
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Card"
    post:
      summary: Creates a card
      tags:
      - Cards
      parameters: []
      responses:
        '201':
          description: card created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Card"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CardInput"
  "/api/cards/{uuid}":
    parameters:
    - name: uuid
      in: path
      required: true
      schema:
        type: string
    put:
      summary: Updates a card
      tags:
      - Cards
      parameters: []
      responses:
        '200':
          description: card updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Card"
        '404':
          description: card not found
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CardInput"
  "/api/owner/cards":
    post:
      summary: Creates a card
      tags:
      - Owner Cards
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: card created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OwnerCard"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CardInput"
  "/api/owner/tags":
    post:
      summary: Creates a tag
      tags:
      - Owner Tags
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: tag created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OwnerTag"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TagInput"
  "/api/tags/{tag_slug}/cards":
    parameters:
    - name: tag_slug
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Lists cards belonging to a tag
      tags:
      - Tags
      responses:
        '200':
          description: cards listed
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Card"
        '404':
          description: tag not found
  "/api/tags":
    get:
      summary: Lists tags
      tags:
      - Tags
      responses:
        '200':
          description: tags listed
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Tag"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    Card:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        pinyin:
          type: string
        tags:
          type: array
          items:
            "$ref": "#/components/schemas/Tag"
      required:
      - uuid
      - name
      - pinyin
      - tags
    Tag:
      type: object
      properties:
        slug:
          type: string
        name:
          type: string
      required:
      - slug
      - name
    OwnerCard:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
        name:
          type: string
        pinyin:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - uuid
      - name
      - pinyin
      - created_at
      - updated_at
    OwnerTag:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
      - slug
      - created_at
      - updated_at
    CardInput:
      type: object
      properties:
        card:
          type: object
          properties:
            name:
              type: string
            pinyin:
              type: string
          required:
          - name
          - pinyin
      required:
      - card
    TagInput:
      type: object
      properties:
        tag:
          type: object
          properties:
            name:
              type: string
            slug:
              type: string
          required:
          - name
          - slug
      required:
      - tag
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      required:
      - errors
